version: '3'
services:
  web:
    build: .
    command: sh -c "python read_dbf_to_redis.py && python server.py"
    depends_on:
      - redis
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      REDIS_URI: redis
      REDIS_PORT: 6379
  redis:
    image: redis:4-alpine